project:
  type: website
  output-dir: ../docs

website:
  title: "libcoral"
  # navbar:
  #   left:
  #     - href: index.qmd
  sidebar:
    #style: "docked"
    search: true
    contents:
      - section: "Introduction"
        href: index.qmd
      - section: "Algorithms"
        href: diversity.qmd
        contents:
          - diversity.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true




