[package]
name = "libcoral"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
log = "0.4.22"
pyo3 = { version="0.21", optional=true }

[dev-dependencies]
ndarray-rand = "0.14.0"

[features]
pyo3 = ["dep:pyo3"]

